-- 1) Create database

CREATE DATABASE bootcamp;

-- 2) Create table students
CREATE TABLE IF NOT EXISTS public.students (
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
first_name TEXT NOT NULL,
last_name TEXT NOT NULL,
birth_date DATE NOT NULL
);

-- 3) Insert data (efficient multi-row INSERT)

INSERT INTO public.students (first_name, last_name, birth_date) VALUES
('Marc', 'Benichou', '1998-11-02'),
('Yoan', 'Cohen', '2010-12-03'),
('Lea', 'Benichou', '1987-07-27'),
('Amelia', 'Dux', '1996-04-07'),
('David', 'Grez', '2003-06-14'),
('Omer', 'Simpson', '1980-10-03');

-- 3b) Insert your own row (id will auto-increment)

INSERT INTO public.students (first_name, last_name, birth_date)
VALUES ('YourFirstName', 'YourLastName', '2000-01-15');

-- 4) SELECT queries

-- a) Fetch all data
SELECT * FROM public.students;

-- b) Fetch all first_names and last_names
SELECT first_name, last_name FROM public.students;


-- c) Student with id = 2
SELECT first_name, last_name
FROM public.students
WHERE id = 2;

-- d) last_name = 'Benichou' AND first_name = 'Marc'
SELECT first_name, last_name
FROM public.students
WHERE last_name = 'Benichou' AND first_name = 'Marc';

-- e) last_name = 'Benichou' OR first_name = 'Marc'
SELECT first_name, last_name
FROM public.students
WHERE last_name = 'Benichou' OR first_name = 'Marc';

-- f) first_names contain the letter 'a' (case-insensitive)
SELECT first_name, last_name
FROM public.students
WHERE first_name ILIKE '%a%';

-- g) first_names start with 'a' (case-insensitive)
SELECT first_name, last_name
FROM public.students
WHERE first_name ILIKE 'a%';

-- h) first_names end with 'a' (case-insensitive)
SELECT first_name, last_name
FROM public.students
WHERE first_name ILIKE '%a';

-- i) second-to-last letter of first_name is 'a'

SELECT first_name, last_name
FROM public.students
WHERE first_name ILIKE '%a_';

-- j) ids are equal to 1 AND 3 (no row can be both 1 and 3 at once)

SELECT first_name, last_name
FROM public.students
WHERE id = 1 AND id = 3;

-- k) birth_dates on or after 2000-01-01 (show all info)
SELECT *
FROM public.students
WHERE birth_date >= DATE '2000-01-01';